# Generated by Django 2.2.2 on 2019-06-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='api.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='timestamp',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
