# Generated by Django 2.2.2 on 2019-06-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190613_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
