# Generated by Django 2.2.2 on 2019-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190613_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, to='api.Product'),
        ),
    ]
