# Generated by Django 2.2.1 on 2019-05-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190522_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
    ]
